services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bnp-webapp-prod
    ports:
      - '8080:8080' 
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - bnp-network
    labels:
      - 'traefik.enable=false'

networks:
  bnp-network:
    driver: bridge
